//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointments()
        {
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int AppointmentID { get; set; }
        public int ClientID { get; set; }
        public int EmployeeID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime AppointmentDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Services Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}
