//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmplSpecializ
    {
        public int EmployeeID { get; set; }
        public int ServiceID { get; set; }
        public string cxcdc { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Services Services { get; set; }
    }
}
