//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHistory
    {
        public int PurchaseID { get; set; }
        public int UserID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public decimal ActualPrice { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
    }
}
